[default]
list:
  just --list

[arg('day', pattern='\d{2}')]
template day:
  cargo generate --path template --name "aoc_2025_{{day}}"

[arg('day', pattern='\d{2}|\*')]
[arg('part', pattern='[12\*]')]
benchmark day="*" part="*":
  cargo bench --color always -q --profile release --bench "aoc_2025_{{day}}-part{{part}}-benchmark"

[arg('day', pattern='\d{2}|\*')]
[arg('part', pattern='[12\*]')]
test day="*" part="*":
  cargo test --color always --package "aoc_2025_{{day}}" --bin "part{{part}}"

[arg('day', pattern='\d{2}')]
[arg('part', pattern='[12]')]
run day part:
  cargo run --color always --package aoc_2025_{{day}} --bin part{{part}}
