[workspace]
members = [
    "aoc_2024_01",
    "aoc_2024_02",
    "aoc_2024_03",
    "aoc_2024_04",
    "aoc_2024_05",
    "aoc_2024_06",
    "aoc_2024_07",
    "common"
]
resolver = "2"

[workspace.dependencies]
common = {path = "./common"}
regex = "1.11.1"
itertools = "0.13.0"
